#!/bin/bash

file_path=$1

if [ -z "$file_path" ]; then
  echo "Usage: $0 <file_path>"
  exit 1
fi

if [ -e "$file_path" ]; then
  echo "$file_path passwords are enabled."

  if [ -w "$file_path" ]; then
    echo "You have permissions to edit $file_path."
  else
    echo "You do NOT have permissions to edit $file_path."
  fi
else
  echo "$file_path does not exist."
fi

