#!/bin/bash

a=$1
b=$2

if [ $# -ne 2 ]; then
  echo "Usage: $0 num1 num2"
  exit 1
fi

if [ $a -gt $b ]; then
  echo "$a is greater than $b"
elif [ $a -lt $b ]; then
  echo "$a is less than $b"
else
  echo "$a is equal to $b"
fi

